export const ProfilePicture: string = "/profile-picture/pfp1.jpg";
export const ProjectDefaultImage: string = "/projects/default-project-img.png";
export const GitHubLink: string = "https://github.com/itsmeprinceyt";
export const YouTubeLink: string = "https://www.youtube.com/@itsmeprinceyt";
export const LinkedInLink: string = "https://www.linkedin.com/in/mohduvaish";
export const X_Link: string = "https://x.com/intent/follow?screen_name=itsmeprinceyt";
export const CodingProjectsLink: string = "https://www.youtube.com/playlist?list=PLiFooJ43_R5SKCLgUOeECaypEXsUv8kEO";
export const DiscordServer_Link: string = "https://discord.gg/HgXNs4p5cx";
export const InstagramLink: string = "https://www.instagram.com/itsmeprinceyt";
export const NOT_WATCHED_ANY_COURSE: string = "I never really followed any course for this — I mostly relied on Google and watched a few YouTube tutorials whenever I got stuck or wasn’t sure what to do next.";
export const GOOGLE_REMINDER: string = "You’ll definitely forget things from time to time — and that’s okay. Just Google it when you need to, but try to recall it on your own first. The longer you can hold onto it before looking it up again, the better it’ll stick.";
export const SKILL_PAGE_LOCKDOWN: boolean = false;